version: 2.1

executors:
  flutter-executor:
    docker:
      - image: cirrusci/flutter:stable
    working_directory: ~/repo

jobs:
  build-apk:
    executor: flutter-executor
    steps:
      - checkout
      - run:
          name: Verify Flutter & Android Environment
          command: |
            flutter doctor -v
      - run:
          name: Install Dependencies
          command: |
            cd flutter_app
            flutter pub get
      - run:
          name: Analyze Code
          command: |
            cd flutter_app
            flutter analyze --no-fatal-infos
      - run:
          name: Build Release Android APK
          command: |
            cd flutter_app
            flutter build apk --release --no-tree-shake-icons
      - store_artifacts:
          path: flutter_app/build/app/outputs/flutter-apk/app-release.apk
          destination: todo-next-android-app/app-release.apk

workflows:
  version: 2
  build-flutter-apk-workflow:
    jobs:
      - build-apk:
          filters:
            branches:
              only:
                - main
                - master
